name: Sky Conduct
favicon: null
layout_spectrum: 0.3127041303087026
typography_spectrum: 0.17655956419184804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.4528829352930188
  lightness: 0.49047148530371487
  saturation: 0.17710894206538796
  rhythmicContrast: 0.4059623726643622
purpose: []
