name: Sky Conduct
favicon: null
layout_spectrum: 0.75688
typography_spectrum: 0.7922810849267989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0099cc'
    - '#000000'
    - '#4e5e6a'
    - '#e5742c'
  brandStrength: 0.625
  lightness: 0.09000477055087686
  saturation: 0
  rhythmicContrast: 1
purpose: []
