name: Sky Conduct
favicon: null
layout_spectrum: 0.12233457714319229
typography_spectrum: 0.7922810849267989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6048885565251112
  lightness: 0.09000477055087686
  saturation: 0.800387623719871
  rhythmicContrast: 0.957678361563012
purpose: []
